
package it.beije.suormary.web.ws.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bookstore", targetNamespace = "http://server.jaxws.ws.web.suormary.beije.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bookstore {


    /**
     * 
     * @return
     *     returns java.util.List<it.beije.suormary.web.ws.jaxws.client.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://server.jaxws.ws.web.suormary.beije.it/", className = "it.beije.suormary.web.ws.jaxws.client.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://server.jaxws.ws.web.suormary.beije.it/", className = "it.beije.suormary.web.ws.jaxws.client.GetBooksResponse")
    @Action(input = "http://server.jaxws.ws.web.suormary.beije.it/Bookstore/getBooksRequest", output = "http://server.jaxws.ws.web.suormary.beije.it/Bookstore/getBooksResponse")
    public List<Book> getBooks();

}
